### PR TITLE
ensure mvvm assemblies are loaded

### PR DESCRIPTION
**Pull request by SimonCropp**
also caches metadataReferences  statically instead of re gen-ing on every test

### CODE REVIEW

**Comment by SimonCropp** [comment]
ok. finally got it working. feel free to squash on merge

**Comment by thomasclaudiushuber** [comment]
Thank you @SimonCropp. Still wonder why it worked on my machine, in CI, and not on yours. Would be interesting to see here what dev environment you have, OS and IDE.

Anyway, moving the refs to a static member and explicitly loading the assembly is a great thing, thank you!

**Comment by SimonCropp** [comment]
i assume you are not using the r# test runner?

**Comment by thomasclaudiushuber** [comment]
No, not on this machine. I have a vanilla VS installation.

**Pull request merged**
